NumPy : Numerical python   
Exploratory Data Analysis

In [ ]:
pip install numpy

In [ ]:
import numpy as np

In [ ]:
a=[1,2,3,4,5]
a

[1, 2, 3, 4, 5]

In [ ]:
arr1=np.array(a)
arr1
# 1D array

array([1, 2, 3, 4, 5])

In [ ]:
arr2=np.array([[1,2,3],[4,5,6]])
arr2
# 2D array

array([[1, 2, 3],
       [4, 5, 6]])

In [ ]:
arr3=np.array([[[1,2,3],[4,5,6]],[[1,3,5],[7,9,11]]])
arr3
# 3D array

array([[[ 1,  2,  3],
        [ 4,  5,  6]],

       [[ 1,  3,  5],
        [ 7,  9, 11]]])

In [ ]:
np.full((3,4),2)

array([[2, 2, 2, 2],
       [2, 2, 2, 2],
       [2, 2, 2, 2]])

In [ ]:
print(type(arr1))
print(type(arr2))
print(type(arr3))

<class 'numpy.ndarray'>
<class 'numpy.ndarray'>
<class 'numpy.ndarray'>


In [ ]:
print("arr1 : ",arr1.shape)
print("arr2 : ",arr2.shape)
print("arr3 : ",arr3.shape)


arr1 :  (5,)
arr2 :  (2, 3)
arr3 :  (2, 2, 3)


In [ ]:
print(arr2)
print(arr2[1,2])
#index of both the rows and columns start from 0.
#the command says : In arr2; from the the row with index 1, print the element with index 2

[[1 2 3]
 [4 5 6]]
6


In [ ]:
arr3

array([[[ 1,  2,  3],
        [ 4,  5,  6]],

       [[ 1,  3,  5],
        [ 7,  9, 11]]])

In [ ]:
arr3[0,1,2]
# 0 - index of the matrix (starting from 0)
# 1 - index of the row
# 2 - index of the element(column)

np.int64(6)

In [ ]:
### make a 1D, 2D, 3D array
D1=np.array([11,12,13])
D2=np.array([[11,12,13],[14,15,16]])
D3=np.array([[[11,12,13],[14,15,16]],[[17,18,19],[20,21,22]]])

print("D1: ",D1)
print(" ")
print("D2: ",D2)
print(" ")
print("D3: ",D3)

D1:  [11 12 13]
 
D2:  [[11 12 13]
 [14 15 16]]
 
D3:  [[[11 12 13]
  [14 15 16]]

 [[17 18 19]
  [20 21 22]]]


In [ ]:
np.zeros((3,4))

array([[0., 0., 0., 0.],
       [0., 0., 0., 0.],
       [0., 0., 0., 0.]])

In [ ]:
np.eye((4))

array([[1., 0., 0., 0.],
       [0., 1., 0., 0.],
       [0., 0., 1., 0.],
       [0., 0., 0., 1.]])

In [ ]:
mat1=np.array([[1,2,3],[2,4,6]])
mat2=np.array([[2,4,1],[2,3,23]])

mat3=mat1+mat2
print(mat1)
print(" ")
print(mat2)
print(" ")
print(mat3)

[[1 2 3]
 [2 4 6]]
 
[[ 2  4  1]
 [ 2  3 23]]
 
[[ 3  6  4]
 [ 4  7 29]]


In [ ]:
mat4=np.array([[1,2],[2,3],[4,5]])
mat4

array([[1, 2],
       [2, 3],
       [4, 5]])

In [ ]:
mat1*mat2

array([[  2,   8,   3],
       [  4,  12, 138]])

In [ ]:
#  mat1*mat4  error
mat1*mat4.T

array([[ 1,  4, 12],
       [ 4, 12, 30]])

In [ ]:
x2=np.random.randint(10,size=(3,4))
x2

array([[6, 1, 7, 3],
       [3, 6, 0, 5],
       [9, 1, 3, 2]])

In [ ]:
x3=np.random.randint(5,size=(3,3,5))
x3

array([[[2, 3, 0, 3, 0],
        [0, 2, 4, 0, 4],
        [3, 2, 3, 1, 1]],

       [[0, 4, 3, 4, 2],
        [3, 1, 1, 3, 0],
        [4, 4, 4, 4, 3]],

       [[0, 3, 3, 2, 1],
        [1, 4, 1, 0, 4],
        [3, 2, 0, 2, 4]]])

In [ ]:
x4=np.random.randint(10,size=(2,2,2))
x5=np.random.randint(10,size=(2,2))
x6=np.random.randint(10,size=(2))
print(x4)
print("----")
print(x5)
print("----")
print(x6)

[[[6 1]
  [6 0]]

 [[1 7]
  [5 2]]]
----
[[7 6]
 [4 7]]
----
[9 3]
